name: Mydockerimage
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build -t myimage .
      

